apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ob0lqu81h-go
  janus-idp.io/tekton: ob0lqu81h-go
  backstage.io/kubernetes-id: ob0lqu81h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ob0lqu81h-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
